export const routesTypes = {
  'SIGN_USER': 'SIGN_USER',
  'ENTER_SMS_CODE': 'ENTER_SMS_CODE',
  'ENTER_PASSWORD': 'ENTER_PASSWORD',
  'CHAT_PAGE': 'USER_PROFILE_PAGE',
  'SEND_PAGE': 'USER_PROFILE_PAGE',
  'WALLET_PAGE': 'WALLET_PAGE',
  'ACTIVITY_PAGE': 'ACTIVITY_PAGE',
  'USER_PROFILE_PAGE': 'USER_PROFILE_PAGE',
  'KYC_PAGE': 'KYC_PAGE',
  'CAMERA_FULL_SCREEN': 'CAMERA_FULL_SCREEN',
  'QR_CODE_FULL_SCREEN': 'QR_CODE_FULL_SCREEN',
}