export const actionTypes = {
  'SIGN_USER_VERIFY_PHONE_REQUEST': 'SIGN_USER_VERIFY_PHONE_REQUEST',
  'SIGN_USER_VERIFY_PHONE_SUCCESS': 'SIGN_USER_VERIFY_PHONE_SUCCESS',
  'SIGN_USER_VERIFY_PHONE_ERROR': 'SIGN_USER_VERIFY_PHONE_ERROR',

  'DETECTION_QR_CODE': 'DETECTION_QR_CODE',
}


// DETECTION_QR_CODE
export const detectionQrCode = data => ({
  type: actionTypes.DETECTION_QR_CODE,
  payload: data
})